<?php
/* This file was generated by the metarefresh module at 2023-05-09T15:05:45Z
*/

$metadata['https://login.aaiedu.hr/sso/saml2/idp/metadata.php'] = array (
  'entityid' => 'https://login.aaiedu.hr/sso/saml2/idp/metadata.php',
  'description' => 
  array (
    'en' => 'AAI@EduHr',
    'hr' => 'AAI@EduHr',
  ),
  'OrganizationName' => 
  array (
    'en' => 'AAI@EduHr',
    'hr' => 'AAI@EduHr',
  ),
  'name' => 
  array (
    'en' => 'AAI@EduHr Single Sign-On Service',
    'hr' => 'AAI@EduHr sustav jedinstvene autentikacije korisnika',
  ),
  'OrganizationDisplayName' => 
  array (
    'en' => 'AAI@EduHr - Croatian Research and Education Federation',
    'hr' => 'AAI@EduHr - Autentikacijska i autorizacijska infrastruktura sustava znanosti i visokog obrazovanja u Republici Hrvatskoj',
  ),
  'url' => 
  array (
    'en' => 'https://www.aaiedu.hr',
    'hr' => 'https://www.aaiedu.hr',
  ),
  'OrganizationURL' => 
  array (
    'en' => 'https://www.aaiedu.hr',
    'hr' => 'https://www.aaiedu.hr',
  ),
  'contacts' => 
  array (
    0 => 
    array (
      'contactType' => 'technical',
      'givenName' => 'AAI@EduHr technical support service',
      'emailAddress' => 
      array (
        0 => 'aosi@aaiedu.hr',
      ),
    ),
  ),
  'metadata-set' => 'saml20-idp-remote',
  'SingleSignOnService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://login.aaiedu.hr/sso/saml2/idp/SSOService.php',
    ),
  ),
  'SingleLogoutService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://login.aaiedu.hr/sso/saml2/idp/SingleLogoutService.php',
    ),
  ),
  'ArtifactResolutionService' => 
  array (
  ),
  'NameIDFormats' => 
  array (
    0 => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
  ),
  'keys' => 
  array (
    0 => 
    array (
      'encryption' => false,
      'signing' => true,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIE8TCCA1mgAwIBAgIUHmiNQLyUJbl9cwqM6lJkKfHzTMcwDQYJKoZIhvcNAQELBQAwgYcxCzAJBgNVBAYTAkhSMQ8wDQYDVQQIDAZaYWdyZWIxDzANBgNVBAcMBlphZ3JlYjESMBAGA1UECgwJQUFJQEVkdUhyMQwwCgYDVQQLDANBQUkxGDAWBgNVBAMMD2xvZ2luLmFhaWVkdS5ocjEaMBgGCSqGSIb3DQEJARYLYWFpQHNyY2UuaHIwHhcNMjMwNTAyMDY1ODA4WhcNMzMwNTAxMDY1ODA4WjCBhzELMAkGA1UEBhMCSFIxDzANBgNVBAgMBlphZ3JlYjEPMA0GA1UEBwwGWmFncmViMRIwEAYDVQQKDAlBQUlARWR1SHIxDDAKBgNVBAsMA0FBSTEYMBYGA1UEAwwPbG9naW4uYWFpZWR1LmhyMRowGAYJKoZIhvcNAQkBFgthYWlAc3JjZS5ocjCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMsKFB6Np2oBGq4TS0L5RKm3svIFWHY029nmBwTXwPGoptfJ1JEw9oYKWTTaBu24bZp2ffOvO90/gvNO08Wg3pJcn95d5NCEY13XNogCU/JmH+DfUMVSFSuzxcIphXd4xOahRBQYRHytGhV14mjAj4qrQYceC5EKM9ESAiJkLdrq7rcC/zv3XL0329pf6OsmRKuWv3OYnvGJqkZ6R7ArhREJbncnTbSBcXN//+cDFRog2GZPfcDQU/67wtcFMWQQ2QI8U/7cnLjzTVz4DoXdsltihKmVVptJKztpq6sx05KSFVyHwDVyeXsUI70T96HAPTrArM1X0TkPd7CjxYb17trVZL7vDsQDnVnHi/2NtaZxIlDdW4Z8s5EG3XIc6vugHshGAFLiZPmguNWES5NTrU4awOL93vKz5fNq4BQ2Kq2R1nYChAdLCDLT+HYjzHwBIlbHtF/gHkpLh98Q1aemQr1pX4TLlOFCcP32WRI2tR/Yhtjv5SiAmxqBsEveuWGrTwIDAQABo1MwUTAdBgNVHQ4EFgQU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwHwYDVR0jBBgwFoAU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAYEAA/H0D8io3K97kRfx1k9Nn0PosxbXouCBtPDx0JaWS3qaqfWwVQBus514MndrAZQuF3hTQoDvWEDfQcHZXTJ923dJsddkB6oPyEdm4n3knraJ2ZQy62/Fkm60t0e2fsjaEhCrWP8F66PNtVqLPadxM1rnDFB8aGgwyinvEiDiyJzwUPz/BAoM2nmV3dStAnIBO5+0FvPQDoXMI9/XCPZka9AjRrSMCSIEaua/gLGie2jMOiPfRxRrUvZp5tC6zHZwlQGLWcRXtZmay2RjtCwdAWp0OGRMewgS3KjC+4/R6l7zNSd3dO9FbT4YoKciBpis2atRA+yLMgaC7ulCXV8K+mLA/clNPVhinHdoG467J8KxYBgnkZGFskrBr+z5DILab5syjxJp564tts1544dWgpY0oQxxFGnSSRqMHZVJLRgqw5GE5nt0UfUrqX5YQQGIwz2qldrP/eYvLRZSJM8GLDlWUSQLL38vnKYcP9QklmFoLbe0t1Mnkz3BMKree16e',
    ),
    1 => 
    array (
      'encryption' => true,
      'signing' => false,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIE8TCCA1mgAwIBAgIUHmiNQLyUJbl9cwqM6lJkKfHzTMcwDQYJKoZIhvcNAQELBQAwgYcxCzAJBgNVBAYTAkhSMQ8wDQYDVQQIDAZaYWdyZWIxDzANBgNVBAcMBlphZ3JlYjESMBAGA1UECgwJQUFJQEVkdUhyMQwwCgYDVQQLDANBQUkxGDAWBgNVBAMMD2xvZ2luLmFhaWVkdS5ocjEaMBgGCSqGSIb3DQEJARYLYWFpQHNyY2UuaHIwHhcNMjMwNTAyMDY1ODA4WhcNMzMwNTAxMDY1ODA4WjCBhzELMAkGA1UEBhMCSFIxDzANBgNVBAgMBlphZ3JlYjEPMA0GA1UEBwwGWmFncmViMRIwEAYDVQQKDAlBQUlARWR1SHIxDDAKBgNVBAsMA0FBSTEYMBYGA1UEAwwPbG9naW4uYWFpZWR1LmhyMRowGAYJKoZIhvcNAQkBFgthYWlAc3JjZS5ocjCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMsKFB6Np2oBGq4TS0L5RKm3svIFWHY029nmBwTXwPGoptfJ1JEw9oYKWTTaBu24bZp2ffOvO90/gvNO08Wg3pJcn95d5NCEY13XNogCU/JmH+DfUMVSFSuzxcIphXd4xOahRBQYRHytGhV14mjAj4qrQYceC5EKM9ESAiJkLdrq7rcC/zv3XL0329pf6OsmRKuWv3OYnvGJqkZ6R7ArhREJbncnTbSBcXN//+cDFRog2GZPfcDQU/67wtcFMWQQ2QI8U/7cnLjzTVz4DoXdsltihKmVVptJKztpq6sx05KSFVyHwDVyeXsUI70T96HAPTrArM1X0TkPd7CjxYb17trVZL7vDsQDnVnHi/2NtaZxIlDdW4Z8s5EG3XIc6vugHshGAFLiZPmguNWES5NTrU4awOL93vKz5fNq4BQ2Kq2R1nYChAdLCDLT+HYjzHwBIlbHtF/gHkpLh98Q1aemQr1pX4TLlOFCcP32WRI2tR/Yhtjv5SiAmxqBsEveuWGrTwIDAQABo1MwUTAdBgNVHQ4EFgQU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwHwYDVR0jBBgwFoAU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAYEAA/H0D8io3K97kRfx1k9Nn0PosxbXouCBtPDx0JaWS3qaqfWwVQBus514MndrAZQuF3hTQoDvWEDfQcHZXTJ923dJsddkB6oPyEdm4n3knraJ2ZQy62/Fkm60t0e2fsjaEhCrWP8F66PNtVqLPadxM1rnDFB8aGgwyinvEiDiyJzwUPz/BAoM2nmV3dStAnIBO5+0FvPQDoXMI9/XCPZka9AjRrSMCSIEaua/gLGie2jMOiPfRxRrUvZp5tC6zHZwlQGLWcRXtZmay2RjtCwdAWp0OGRMewgS3KjC+4/R6l7zNSd3dO9FbT4YoKciBpis2atRA+yLMgaC7ulCXV8K+mLA/clNPVhinHdoG467J8KxYBgnkZGFskrBr+z5DILab5syjxJp564tts1544dWgpY0oQxxFGnSSRqMHZVJLRgqw5GE5nt0UfUrqX5YQQGIwz2qldrP/eYvLRZSJM8GLDlWUSQLL38vnKYcP9QklmFoLbe0t1Mnkz3BMKree16e',
    ),
  ),
  'UIInfo' => 
  array (
    'DisplayName' => 
    array (
      'en' => 'AAI@EduHr Single Sign-On Service',
      'hr' => 'AAI@EduHr sustav jedinstvene autentikacije korisnika',
    ),
    'Description' => 
    array (
      'en' => 'Central Login Service for the AAI@EduHr Federation with implemented Single Sign-On Feature',
      'hr' => 'Središnji autentikacijski servis AAI@EduHr federacije s implementiranim sustavom jedinstvene autentikacije korisnika',
    ),
    'InformationURL' => 
    array (
    ),
    'PrivacyStatementURL' => 
    array (
    ),
  ),
  'metarefresh:src' => 'https://login.aaiedu.hr/sso/saml2/idp/metadata.php',
);

$metadata['https://login.aaiedu.hr/proxy/saml2/idp/metadata.php'] = array (
  'entityid' => 'https://login.aaiedu.hr/proxy/saml2/idp/metadata.php',
  'contacts' => 
  array (
    0 => 
    array (
      'contactType' => 'technical',
      'givenName' => 'AAI@EduHr technical support service',
      'emailAddress' => 
      array (
        0 => 'aosi@aaiedu.hr',
      ),
    ),
  ),
  'metadata-set' => 'saml20-idp-remote',
  'SingleSignOnService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://login.aaiedu.hr/proxy/saml2/idp/SSOService.php',
    ),
  ),
  'SingleLogoutService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://login.aaiedu.hr/proxy/saml2/idp/SingleLogoutService.php',
    ),
  ),
  'ArtifactResolutionService' => 
  array (
  ),
  'NameIDFormats' => 
  array (
    0 => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
  ),
  'keys' => 
  array (
    0 => 
    array (
      'encryption' => false,
      'signing' => true,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIE8TCCA1mgAwIBAgIUHmiNQLyUJbl9cwqM6lJkKfHzTMcwDQYJKoZIhvcNAQELBQAwgYcxCzAJBgNVBAYTAkhSMQ8wDQYDVQQIDAZaYWdyZWIxDzANBgNVBAcMBlphZ3JlYjESMBAGA1UECgwJQUFJQEVkdUhyMQwwCgYDVQQLDANBQUkxGDAWBgNVBAMMD2xvZ2luLmFhaWVkdS5ocjEaMBgGCSqGSIb3DQEJARYLYWFpQHNyY2UuaHIwHhcNMjMwNTAyMDY1ODA4WhcNMzMwNTAxMDY1ODA4WjCBhzELMAkGA1UEBhMCSFIxDzANBgNVBAgMBlphZ3JlYjEPMA0GA1UEBwwGWmFncmViMRIwEAYDVQQKDAlBQUlARWR1SHIxDDAKBgNVBAsMA0FBSTEYMBYGA1UEAwwPbG9naW4uYWFpZWR1LmhyMRowGAYJKoZIhvcNAQkBFgthYWlAc3JjZS5ocjCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMsKFB6Np2oBGq4TS0L5RKm3svIFWHY029nmBwTXwPGoptfJ1JEw9oYKWTTaBu24bZp2ffOvO90/gvNO08Wg3pJcn95d5NCEY13XNogCU/JmH+DfUMVSFSuzxcIphXd4xOahRBQYRHytGhV14mjAj4qrQYceC5EKM9ESAiJkLdrq7rcC/zv3XL0329pf6OsmRKuWv3OYnvGJqkZ6R7ArhREJbncnTbSBcXN//+cDFRog2GZPfcDQU/67wtcFMWQQ2QI8U/7cnLjzTVz4DoXdsltihKmVVptJKztpq6sx05KSFVyHwDVyeXsUI70T96HAPTrArM1X0TkPd7CjxYb17trVZL7vDsQDnVnHi/2NtaZxIlDdW4Z8s5EG3XIc6vugHshGAFLiZPmguNWES5NTrU4awOL93vKz5fNq4BQ2Kq2R1nYChAdLCDLT+HYjzHwBIlbHtF/gHkpLh98Q1aemQr1pX4TLlOFCcP32WRI2tR/Yhtjv5SiAmxqBsEveuWGrTwIDAQABo1MwUTAdBgNVHQ4EFgQU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwHwYDVR0jBBgwFoAU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAYEAA/H0D8io3K97kRfx1k9Nn0PosxbXouCBtPDx0JaWS3qaqfWwVQBus514MndrAZQuF3hTQoDvWEDfQcHZXTJ923dJsddkB6oPyEdm4n3knraJ2ZQy62/Fkm60t0e2fsjaEhCrWP8F66PNtVqLPadxM1rnDFB8aGgwyinvEiDiyJzwUPz/BAoM2nmV3dStAnIBO5+0FvPQDoXMI9/XCPZka9AjRrSMCSIEaua/gLGie2jMOiPfRxRrUvZp5tC6zHZwlQGLWcRXtZmay2RjtCwdAWp0OGRMewgS3KjC+4/R6l7zNSd3dO9FbT4YoKciBpis2atRA+yLMgaC7ulCXV8K+mLA/clNPVhinHdoG467J8KxYBgnkZGFskrBr+z5DILab5syjxJp564tts1544dWgpY0oQxxFGnSSRqMHZVJLRgqw5GE5nt0UfUrqX5YQQGIwz2qldrP/eYvLRZSJM8GLDlWUSQLL38vnKYcP9QklmFoLbe0t1Mnkz3BMKree16e',
    ),
    1 => 
    array (
      'encryption' => true,
      'signing' => false,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIE8TCCA1mgAwIBAgIUHmiNQLyUJbl9cwqM6lJkKfHzTMcwDQYJKoZIhvcNAQELBQAwgYcxCzAJBgNVBAYTAkhSMQ8wDQYDVQQIDAZaYWdyZWIxDzANBgNVBAcMBlphZ3JlYjESMBAGA1UECgwJQUFJQEVkdUhyMQwwCgYDVQQLDANBQUkxGDAWBgNVBAMMD2xvZ2luLmFhaWVkdS5ocjEaMBgGCSqGSIb3DQEJARYLYWFpQHNyY2UuaHIwHhcNMjMwNTAyMDY1ODA4WhcNMzMwNTAxMDY1ODA4WjCBhzELMAkGA1UEBhMCSFIxDzANBgNVBAgMBlphZ3JlYjEPMA0GA1UEBwwGWmFncmViMRIwEAYDVQQKDAlBQUlARWR1SHIxDDAKBgNVBAsMA0FBSTEYMBYGA1UEAwwPbG9naW4uYWFpZWR1LmhyMRowGAYJKoZIhvcNAQkBFgthYWlAc3JjZS5ocjCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMsKFB6Np2oBGq4TS0L5RKm3svIFWHY029nmBwTXwPGoptfJ1JEw9oYKWTTaBu24bZp2ffOvO90/gvNO08Wg3pJcn95d5NCEY13XNogCU/JmH+DfUMVSFSuzxcIphXd4xOahRBQYRHytGhV14mjAj4qrQYceC5EKM9ESAiJkLdrq7rcC/zv3XL0329pf6OsmRKuWv3OYnvGJqkZ6R7ArhREJbncnTbSBcXN//+cDFRog2GZPfcDQU/67wtcFMWQQ2QI8U/7cnLjzTVz4DoXdsltihKmVVptJKztpq6sx05KSFVyHwDVyeXsUI70T96HAPTrArM1X0TkPd7CjxYb17trVZL7vDsQDnVnHi/2NtaZxIlDdW4Z8s5EG3XIc6vugHshGAFLiZPmguNWES5NTrU4awOL93vKz5fNq4BQ2Kq2R1nYChAdLCDLT+HYjzHwBIlbHtF/gHkpLh98Q1aemQr1pX4TLlOFCcP32WRI2tR/Yhtjv5SiAmxqBsEveuWGrTwIDAQABo1MwUTAdBgNVHQ4EFgQU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwHwYDVR0jBBgwFoAU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAYEAA/H0D8io3K97kRfx1k9Nn0PosxbXouCBtPDx0JaWS3qaqfWwVQBus514MndrAZQuF3hTQoDvWEDfQcHZXTJ923dJsddkB6oPyEdm4n3knraJ2ZQy62/Fkm60t0e2fsjaEhCrWP8F66PNtVqLPadxM1rnDFB8aGgwyinvEiDiyJzwUPz/BAoM2nmV3dStAnIBO5+0FvPQDoXMI9/XCPZka9AjRrSMCSIEaua/gLGie2jMOiPfRxRrUvZp5tC6zHZwlQGLWcRXtZmay2RjtCwdAWp0OGRMewgS3KjC+4/R6l7zNSd3dO9FbT4YoKciBpis2atRA+yLMgaC7ulCXV8K+mLA/clNPVhinHdoG467J8KxYBgnkZGFskrBr+z5DILab5syjxJp564tts1544dWgpY0oQxxFGnSSRqMHZVJLRgqw5GE5nt0UfUrqX5YQQGIwz2qldrP/eYvLRZSJM8GLDlWUSQLL38vnKYcP9QklmFoLbe0t1Mnkz3BMKree16e',
    ),
  ),
  'metarefresh:src' => 'https://login.aaiedu.hr/proxy/saml2/idp/metadata.php',
);

$metadata['https://login.aaiedu.hr/mfa/saml2/idp/metadata.php'] = array (
  'entityid' => 'https://login.aaiedu.hr/mfa/saml2/idp/metadata.php',
  'contacts' => 
  array (
    0 => 
    array (
      'contactType' => 'technical',
      'givenName' => 'AAI@EduHr technical support service',
      'emailAddress' => 
      array (
        0 => 'aosi@aaiedu.hr',
      ),
    ),
  ),
  'metadata-set' => 'saml20-idp-remote',
  'SingleSignOnService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://login.aaiedu.hr/mfa/saml2/idp/SSOService.php',
    ),
  ),
  'SingleLogoutService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://login.aaiedu.hr/mfa/saml2/idp/SingleLogoutService.php',
    ),
  ),
  'ArtifactResolutionService' => 
  array (
  ),
  'NameIDFormats' => 
  array (
    0 => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
  ),
  'keys' => 
  array (
    0 => 
    array (
      'encryption' => false,
      'signing' => true,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIE8TCCA1mgAwIBAgIUHmiNQLyUJbl9cwqM6lJkKfHzTMcwDQYJKoZIhvcNAQELBQAwgYcxCzAJBgNVBAYTAkhSMQ8wDQYDVQQIDAZaYWdyZWIxDzANBgNVBAcMBlphZ3JlYjESMBAGA1UECgwJQUFJQEVkdUhyMQwwCgYDVQQLDANBQUkxGDAWBgNVBAMMD2xvZ2luLmFhaWVkdS5ocjEaMBgGCSqGSIb3DQEJARYLYWFpQHNyY2UuaHIwHhcNMjMwNTAyMDY1ODA4WhcNMzMwNTAxMDY1ODA4WjCBhzELMAkGA1UEBhMCSFIxDzANBgNVBAgMBlphZ3JlYjEPMA0GA1UEBwwGWmFncmViMRIwEAYDVQQKDAlBQUlARWR1SHIxDDAKBgNVBAsMA0FBSTEYMBYGA1UEAwwPbG9naW4uYWFpZWR1LmhyMRowGAYJKoZIhvcNAQkBFgthYWlAc3JjZS5ocjCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMsKFB6Np2oBGq4TS0L5RKm3svIFWHY029nmBwTXwPGoptfJ1JEw9oYKWTTaBu24bZp2ffOvO90/gvNO08Wg3pJcn95d5NCEY13XNogCU/JmH+DfUMVSFSuzxcIphXd4xOahRBQYRHytGhV14mjAj4qrQYceC5EKM9ESAiJkLdrq7rcC/zv3XL0329pf6OsmRKuWv3OYnvGJqkZ6R7ArhREJbncnTbSBcXN//+cDFRog2GZPfcDQU/67wtcFMWQQ2QI8U/7cnLjzTVz4DoXdsltihKmVVptJKztpq6sx05KSFVyHwDVyeXsUI70T96HAPTrArM1X0TkPd7CjxYb17trVZL7vDsQDnVnHi/2NtaZxIlDdW4Z8s5EG3XIc6vugHshGAFLiZPmguNWES5NTrU4awOL93vKz5fNq4BQ2Kq2R1nYChAdLCDLT+HYjzHwBIlbHtF/gHkpLh98Q1aemQr1pX4TLlOFCcP32WRI2tR/Yhtjv5SiAmxqBsEveuWGrTwIDAQABo1MwUTAdBgNVHQ4EFgQU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwHwYDVR0jBBgwFoAU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAYEAA/H0D8io3K97kRfx1k9Nn0PosxbXouCBtPDx0JaWS3qaqfWwVQBus514MndrAZQuF3hTQoDvWEDfQcHZXTJ923dJsddkB6oPyEdm4n3knraJ2ZQy62/Fkm60t0e2fsjaEhCrWP8F66PNtVqLPadxM1rnDFB8aGgwyinvEiDiyJzwUPz/BAoM2nmV3dStAnIBO5+0FvPQDoXMI9/XCPZka9AjRrSMCSIEaua/gLGie2jMOiPfRxRrUvZp5tC6zHZwlQGLWcRXtZmay2RjtCwdAWp0OGRMewgS3KjC+4/R6l7zNSd3dO9FbT4YoKciBpis2atRA+yLMgaC7ulCXV8K+mLA/clNPVhinHdoG467J8KxYBgnkZGFskrBr+z5DILab5syjxJp564tts1544dWgpY0oQxxFGnSSRqMHZVJLRgqw5GE5nt0UfUrqX5YQQGIwz2qldrP/eYvLRZSJM8GLDlWUSQLL38vnKYcP9QklmFoLbe0t1Mnkz3BMKree16e',
    ),
    1 => 
    array (
      'encryption' => true,
      'signing' => false,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIE8TCCA1mgAwIBAgIUHmiNQLyUJbl9cwqM6lJkKfHzTMcwDQYJKoZIhvcNAQELBQAwgYcxCzAJBgNVBAYTAkhSMQ8wDQYDVQQIDAZaYWdyZWIxDzANBgNVBAcMBlphZ3JlYjESMBAGA1UECgwJQUFJQEVkdUhyMQwwCgYDVQQLDANBQUkxGDAWBgNVBAMMD2xvZ2luLmFhaWVkdS5ocjEaMBgGCSqGSIb3DQEJARYLYWFpQHNyY2UuaHIwHhcNMjMwNTAyMDY1ODA4WhcNMzMwNTAxMDY1ODA4WjCBhzELMAkGA1UEBhMCSFIxDzANBgNVBAgMBlphZ3JlYjEPMA0GA1UEBwwGWmFncmViMRIwEAYDVQQKDAlBQUlARWR1SHIxDDAKBgNVBAsMA0FBSTEYMBYGA1UEAwwPbG9naW4uYWFpZWR1LmhyMRowGAYJKoZIhvcNAQkBFgthYWlAc3JjZS5ocjCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMsKFB6Np2oBGq4TS0L5RKm3svIFWHY029nmBwTXwPGoptfJ1JEw9oYKWTTaBu24bZp2ffOvO90/gvNO08Wg3pJcn95d5NCEY13XNogCU/JmH+DfUMVSFSuzxcIphXd4xOahRBQYRHytGhV14mjAj4qrQYceC5EKM9ESAiJkLdrq7rcC/zv3XL0329pf6OsmRKuWv3OYnvGJqkZ6R7ArhREJbncnTbSBcXN//+cDFRog2GZPfcDQU/67wtcFMWQQ2QI8U/7cnLjzTVz4DoXdsltihKmVVptJKztpq6sx05KSFVyHwDVyeXsUI70T96HAPTrArM1X0TkPd7CjxYb17trVZL7vDsQDnVnHi/2NtaZxIlDdW4Z8s5EG3XIc6vugHshGAFLiZPmguNWES5NTrU4awOL93vKz5fNq4BQ2Kq2R1nYChAdLCDLT+HYjzHwBIlbHtF/gHkpLh98Q1aemQr1pX4TLlOFCcP32WRI2tR/Yhtjv5SiAmxqBsEveuWGrTwIDAQABo1MwUTAdBgNVHQ4EFgQU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwHwYDVR0jBBgwFoAU2i6ViqqYXMPU40sa4Ssi2Z0xGVkwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAYEAA/H0D8io3K97kRfx1k9Nn0PosxbXouCBtPDx0JaWS3qaqfWwVQBus514MndrAZQuF3hTQoDvWEDfQcHZXTJ923dJsddkB6oPyEdm4n3knraJ2ZQy62/Fkm60t0e2fsjaEhCrWP8F66PNtVqLPadxM1rnDFB8aGgwyinvEiDiyJzwUPz/BAoM2nmV3dStAnIBO5+0FvPQDoXMI9/XCPZka9AjRrSMCSIEaua/gLGie2jMOiPfRxRrUvZp5tC6zHZwlQGLWcRXtZmay2RjtCwdAWp0OGRMewgS3KjC+4/R6l7zNSd3dO9FbT4YoKciBpis2atRA+yLMgaC7ulCXV8K+mLA/clNPVhinHdoG467J8KxYBgnkZGFskrBr+z5DILab5syjxJp564tts1544dWgpY0oQxxFGnSSRqMHZVJLRgqw5GE5nt0UfUrqX5YQQGIwz2qldrP/eYvLRZSJM8GLDlWUSQLL38vnKYcP9QklmFoLbe0t1Mnkz3BMKree16e',
    ),
  ),
  'metarefresh:src' => 'https://login.aaiedu.hr/mfa/saml2/idp/metadata.php',
);

$metadata['https://fed-lab.aaiedu.hr/sso/saml2/idp/metadata.php'] = array (
  'entityid' => 'https://fed-lab.aaiedu.hr/sso/saml2/idp/metadata.php',
  'description' => 
  array (
    'en' => 'AAI@EduHr',
    'hr' => 'AAI@EduHr',
  ),
  'OrganizationName' => 
  array (
    'en' => 'AAI@EduHr',
    'hr' => 'AAI@EduHr',
  ),
  'name' => 
  array (
    'en' => 'AAI@EduHr Single Sign-On Service',
    'hr' => 'AAI@EduHr sustav jedinstvene autentikacije korisnika',
  ),
  'OrganizationDisplayName' => 
  array (
    'en' => 'AAI@EduHr - Croatian Research and Education Federation',
    'hr' => 'AAI@EduHr - Autentikacijska i autorizacijska infrastruktura sustava znanosti i visokog obrazovanja u Republici Hrvatskoj',
  ),
  'url' => 
  array (
    'en' => 'https://www.aaiedu.hr',
    'hr' => 'https://www.aaiedu.hr',
  ),
  'OrganizationURL' => 
  array (
    'en' => 'https://www.aaiedu.hr',
    'hr' => 'https://www.aaiedu.hr',
  ),
  'contacts' => 
  array (
    0 => 
    array (
      'contactType' => 'technical',
      'givenName' => 'AAI@EduHr technical support service',
      'emailAddress' => 
      array (
        0 => 'aosi@aaiedu.hr',
      ),
    ),
  ),
  'metadata-set' => 'saml20-idp-remote',
  'SingleSignOnService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://fed-lab.aaiedu.hr/sso/saml2/idp/SSOService.php',
    ),
  ),
  'SingleLogoutService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://fed-lab.aaiedu.hr/sso/saml2/idp/SingleLogoutService.php',
    ),
  ),
  'ArtifactResolutionService' => 
  array (
  ),
  'NameIDFormats' => 
  array (
    0 => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
  ),
  'keys' => 
  array (
    0 => 
    array (
      'encryption' => false,
      'signing' => true,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIE9TCCA12gAwIBAgIULU240s3O3ahvDLReR58bnqupN7cwDQYJKoZIhvcNAQELBQAwgYkxCzAJBgNVBAYTAkhSMQ8wDQYDVQQIDAZaYWdyZWIxDzANBgNVBAcMBlphZ3JlYjESMBAGA1UECgwJQUFJQEVkdUhyMQwwCgYDVQQLDANBQUkxGjAYBgNVBAMMEWZlZC1sYWIuYWFpZWR1LmhyMRowGAYJKoZIhvcNAQkBFgthYWlAc3JjZS5ocjAeFw0yMzA1MDQwNDA5MzlaFw0zMzA1MDMwNDA5MzlaMIGJMQswCQYDVQQGEwJIUjEPMA0GA1UECAwGWmFncmViMQ8wDQYDVQQHDAZaYWdyZWIxEjAQBgNVBAoMCUFBSUBFZHVIcjEMMAoGA1UECwwDQUFJMRowGAYDVQQDDBFmZWQtbGFiLmFhaWVkdS5ocjEaMBgGCSqGSIb3DQEJARYLYWFpQHNyY2UuaHIwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQC5AvFI/i5zo18yGoZx35a0a5/b5QEeEAek9SMIL+6HDo6CkogecaK/Hs9iQEEj8auuH8v1y4/fhte5p7a1mCzQwX/hmCNVrBrKKIEoAKW3aQijwNsSPSqj1Qc7iiIOyWYPPVzLAUp+CgoCSkLI1cd8HnABdel12V1/fD3mhsHsFsrqZUh7gFJTe8efbNiEhlQIuxywoqRLEo2/WiVbHsfs0b9T1CRNzcmx5tbWkR851IkUJ1VcJ0aCcmEzQmw9ex42U5mntB6WC3d3ov8iafogryx+INBTIJTxjxSfvElKqYppbICYH/4eKsTDWSYNxpQDNG62eqqkKma/ZLXaV00hxNOWf6DN9u0mD5wu+UtWqHWJ7F9eWimTk68BYIOXTQr69fL+7l08alKWKkwuyk2BStMngMbqrXqD8qGjEt5rBDBR/2wGf5YmF2AMib453UKjQWQQ4QRD/1LNbIsSkejRFvIBqi0t4f+zxqBq8Na1DD2t9YmwBKnv3lpQjaJizl0CAwEAAaNTMFEwHQYDVR0OBBYEFH+kH0+jA41EHvfyCJhgfIHB1PzKMB8GA1UdIwQYMBaAFH+kH0+jA41EHvfyCJhgfIHB1PzKMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggGBAEgZpRhEVctrHhuwMXOLPrwwtwg3CgVt+Rp8Okgzgl0GnPYYh0YsabNxrmE4QehKLcjPlhT8lAtLruJHuMLX7YzXG1TTgPUh7UpwKJhObkTKzN/bTrDKszE/wqfZ01yqqzY1JsSf000e1P1dr4apFqcrcDJGua2vWsNOo60oWpDcxWZxXkBc9LwOkO9UI6j2l3LlWdGUzP7QSzhPvu6Bb6WdSj+wIeae3MsGM4DEfyvuPHk4Q1rcxBc4AkAQL4vKhJfOEuJ5GScVTIaQVwArHZt2nAeBn9f+JW0NNiTiLKqkjfl3LA+rDg0F2N70NxmgFSWhUo8phGUeP9GqS1z5CBx7XAfrr85BXMBly/ZmXbo5xYgRFXlBzc2QJcNw+gpnzuObNK+s3yV1PChKfa68rkimjNU7DdOyue+VqWswRLTkl3N4GfcVlVnmHnAiY8285wDUljnAe6bwg2iGid1RB0lrAOAmMpjEB1wvhxbGibC2DDyDCF5ipgdWu6CK18CH4w==',
    ),
    1 => 
    array (
      'encryption' => true,
      'signing' => false,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIE9TCCA12gAwIBAgIULU240s3O3ahvDLReR58bnqupN7cwDQYJKoZIhvcNAQELBQAwgYkxCzAJBgNVBAYTAkhSMQ8wDQYDVQQIDAZaYWdyZWIxDzANBgNVBAcMBlphZ3JlYjESMBAGA1UECgwJQUFJQEVkdUhyMQwwCgYDVQQLDANBQUkxGjAYBgNVBAMMEWZlZC1sYWIuYWFpZWR1LmhyMRowGAYJKoZIhvcNAQkBFgthYWlAc3JjZS5ocjAeFw0yMzA1MDQwNDA5MzlaFw0zMzA1MDMwNDA5MzlaMIGJMQswCQYDVQQGEwJIUjEPMA0GA1UECAwGWmFncmViMQ8wDQYDVQQHDAZaYWdyZWIxEjAQBgNVBAoMCUFBSUBFZHVIcjEMMAoGA1UECwwDQUFJMRowGAYDVQQDDBFmZWQtbGFiLmFhaWVkdS5ocjEaMBgGCSqGSIb3DQEJARYLYWFpQHNyY2UuaHIwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQC5AvFI/i5zo18yGoZx35a0a5/b5QEeEAek9SMIL+6HDo6CkogecaK/Hs9iQEEj8auuH8v1y4/fhte5p7a1mCzQwX/hmCNVrBrKKIEoAKW3aQijwNsSPSqj1Qc7iiIOyWYPPVzLAUp+CgoCSkLI1cd8HnABdel12V1/fD3mhsHsFsrqZUh7gFJTe8efbNiEhlQIuxywoqRLEo2/WiVbHsfs0b9T1CRNzcmx5tbWkR851IkUJ1VcJ0aCcmEzQmw9ex42U5mntB6WC3d3ov8iafogryx+INBTIJTxjxSfvElKqYppbICYH/4eKsTDWSYNxpQDNG62eqqkKma/ZLXaV00hxNOWf6DN9u0mD5wu+UtWqHWJ7F9eWimTk68BYIOXTQr69fL+7l08alKWKkwuyk2BStMngMbqrXqD8qGjEt5rBDBR/2wGf5YmF2AMib453UKjQWQQ4QRD/1LNbIsSkejRFvIBqi0t4f+zxqBq8Na1DD2t9YmwBKnv3lpQjaJizl0CAwEAAaNTMFEwHQYDVR0OBBYEFH+kH0+jA41EHvfyCJhgfIHB1PzKMB8GA1UdIwQYMBaAFH+kH0+jA41EHvfyCJhgfIHB1PzKMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggGBAEgZpRhEVctrHhuwMXOLPrwwtwg3CgVt+Rp8Okgzgl0GnPYYh0YsabNxrmE4QehKLcjPlhT8lAtLruJHuMLX7YzXG1TTgPUh7UpwKJhObkTKzN/bTrDKszE/wqfZ01yqqzY1JsSf000e1P1dr4apFqcrcDJGua2vWsNOo60oWpDcxWZxXkBc9LwOkO9UI6j2l3LlWdGUzP7QSzhPvu6Bb6WdSj+wIeae3MsGM4DEfyvuPHk4Q1rcxBc4AkAQL4vKhJfOEuJ5GScVTIaQVwArHZt2nAeBn9f+JW0NNiTiLKqkjfl3LA+rDg0F2N70NxmgFSWhUo8phGUeP9GqS1z5CBx7XAfrr85BXMBly/ZmXbo5xYgRFXlBzc2QJcNw+gpnzuObNK+s3yV1PChKfa68rkimjNU7DdOyue+VqWswRLTkl3N4GfcVlVnmHnAiY8285wDUljnAe6bwg2iGid1RB0lrAOAmMpjEB1wvhxbGibC2DDyDCF5ipgdWu6CK18CH4w==',
    ),
  ),
  'UIInfo' => 
  array (
    'DisplayName' => 
    array (
      'en' => 'AAI@EduHr Single Sign-On Service',
      'hr' => 'AAI@EduHr sustav jedinstvene autentikacije korisnika',
    ),
    'Description' => 
    array (
      'en' => 'Central Login Service for the AAI@EduHr Federation with implemented Single Sign-On Feature',
      'hr' => 'Središnji autentikacijski servis AAI@EduHr federacije s implementiranim sustavom jedinstvene autentikacije korisnika',
    ),
    'InformationURL' => 
    array (
    ),
    'PrivacyStatementURL' => 
    array (
    ),
  ),
  'metarefresh:src' => 'https://fed-lab.aaiedu.hr/sso/saml2/idp/metadata.php',
);
